branches:
  only:
    - master
    
version: 1.0.{build}

image: Visual Studio 2017

install:
  - ps: |
      $msiPath = "$($env:USERPROFILE)\MicrosoftAzureStorageEmulator.msi"
      (New-Object Net.WebClient).DownloadFile('https://download.microsoft.com/download/B/4/A/B4A8422F-C564-4393-80DA-6865A8C4B32D/MicrosoftAzureStorageEmulator.msi', $msiPath)
      cmd /c start /wait msiexec /i $msiPath /quiet
      
# build Configuration, i.e. Debug, Release, etc.
configuration: Release
      
build:
  project: FileManager.Azure.sln      # path to Visual Studio solution or project
  
before_build:
  - dotnet restore
  
after_test:
  - dotnet pack --no-build --configuration $(configuration) --no-restore

test:
  # only assemblies to test
  assemblies:
    only:
      - FileManager.Azure.Tests.dll
      
#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: uiY2o7+IOz9OareLUDrYZHl+NikMs4CByEULjypZ1mSlqfBW6/3hK7yXn54gD0AC
  on:
    branch: master