name: CI

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    
    - name: Install Storage Emulator
      run: |
          $msiPath = "$($env:USERPROFILE)\MicrosoftAzureStorageEmulator.msi"
          (New-Object Net.WebClient).DownloadFile('https://go.microsoft.com/fwlink/?linkid=717179&clcid=0x409', $msiPath)
          cmd /c start /wait msiexec /i $msiPath /quiet
          
    - name: Restore Solution
      run: dotnet restore FileManager.Azure.sln
      
    - name: Build Solution
      run: dotnet build FileManager.Azure.sln  
      
    - name: Test Solution
      run: dotnet test FileManager.Azure.sln
      
    - name: Publish FileManager.Azure
      uses: rohith/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: FileManager.Azure/FileManager.Azure.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
